export const REDUCER_KEY = 'articles';
export const FETCH_ARTICLESLIST_REQUESTED = 'FETCH_ARTICLESLIST_REQUESTED';
export const FETCH_ARTICLESLIST_SUCCESS = 'FETCH_ARTICLESLIST_SUCCESS';
export const FETCH_ARTICLESLIST_FAIL = 'FETCH_ARTICLESLIST_FAIL';
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES';

export const FETCH_GETCUSTOMERBALANCE_REQUESTED = 'FETCH_GETCUSTOMERBALANCE_REQUESTED';
export const FETCH_CUSTOMERBALANCE_SUCCESS = 'FETCH_MORE_WORKS_SUCCESS';
export const FETCH_CUSTOMERBALANCE_FAILED = 'FETCH_MORE_WORKS_FAILED';

export const FETCH_ADDCUSTOMERBALANCE_REQUESTED = 'FETCH_ADDCUSTOMERBALANCE_REQUESTED';
export const FETCH_ADDCUSTOMERBALANCE_SUCCESS = 'FETCH_ADDCUSTOMERBALANCE_SUCCESS';
export const FETCH_ADDCUSTOMERBALANCE_FAILED = 'FETCH_ADDCUSTOMERBALANCE_FAILED';
