export const REDUCER_KEY = 'articles';
export const FETCH_ARTICLESLIST_REQUESTED = 'FETCH_ARTICLESLIST_REQUESTED';
export const FETCH_ARTICLESLIST_SUCCESS = 'FETCH_ARTICLESLIST_SUCCESS';
export const FETCH_ARTICLESLIST_FAIL = 'FETCH_ARTICLESLIST_FAIL';
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES';

