export const REDUCER_KEY = 'payment';
export const FETCH_PAYMENT_REQUESTED = 'FETCH_PAYMENT_REQUESTED';
export const FETCH_PAYMENT_SUCCESS = 'FETCH_PAYMENT_SUCCESS';
export const FETCH_PAYMENT_FAIL = 'FETCH_PAYMENT_FAIL';
export const CLEAR_PAYMENT = 'CLEAR_PAYMENT';
export const CLEAR_ADDMESSAGE = 'CLEAR_ADDMESSAGE';
